SELECT DISTINCT A.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS A, CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B
WHERE A.CAR_ID = B.CAR_ID
    AND A.CAR_TYPE = '세단'
    AND MONTH(B.START_DATE) = 10
ORDER BY CAR_ID DESC;